version: "3.6"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=99
      - PGID=100
      - UMASK=022
      - TZ=America/New_York
      - HOST_OS=Unraid
      - HOST_HOSTNAME=unraid
      - PATH=/lsiopy/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - HOME=/root
      - LANGUAGE=en_US.UTF-8
      - LANG=en_US.UTF-8
      - TERM=xterm
      - S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0
      - S6_VERBOSITY=1
      - S6_STAGE2_HOOK=/docker-mods
      - VIRTUAL_ENV=/lsiopy
      - LSIO_FIRST_PARTY=true
      - XDG_CONFIG_HOME=/config/xdg
    labels:
      traefik.enable: true
      traefik.http.routers.sonarr.entryPoints: https
      traefik.http.routers.sonarr.middlewares: auth@file
      traefik.http.routers.sonarr.rule: Host(`s.arizvi.ca`)
    logging:
      driver: journald
      options: {}
    networks:
      - utilities
    ports:
      - 8989:8989
    volumes:
      - /mnt/unraid/Media/Series:/tv
      - /mnt/unraid/Downloads:/downloads
      - /opt/appdata/sonarr:/config
    working_dir: "/"
    restart: unless-stopped
networks:
  utilities:
    driver: bridge
    external: true
